=== NaokiS28/GenV/schema/fonts.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "schema/fonts.json",
	"title": "Font metrics",
	"type": "object",
	"required": [
		"spaceWidth",
		"tabWidth",
		"lineHeight",
		"baselineOffset",
		"characterSizes"
	],
	"properties": {
		"fontSize": {
			"title": "Font size",
			"description": "Size of the font in pixels.",
			"type": "integer",
			"minimum": 0,
			"maximum": 255
		},
		"flags": {
			"title": "Font flags",
			"description": "Specifies attributes of this font such as whether it is italic or bold",
			"type": "array",
			"items": {
				"type": "string",
				"enum": [
					"italic",
					"bold"
				]
			}
		},
		"spaceWidth": {
			"title": "Space width",
			"description": "Width of the space character in pixels.",
			"type": "integer",
			"minimum": 0,
			"maximum": 255
		},
		"tabWidth": {
			"title": "Tab width",
			"description": "Width of the tab character in pixels.",
			"type": "integer",
			"minimum": 0,
			"maximum": 255
		},
		"lineHeight": {
			"title": "Line height",
			"description": "Height of each line in pixels, including any padding. Characters whose height is lower than this value will be aligned to the top of the line by default.",
			"type": "integer",
			"minimum": 0,
			"maximum": 255
		},
		"baselineOffset": {
			"title": "Baseline offset",
			"description": "Offset to add to the Y coordinate of each line. Can be negative.",
			"type": "integer",
			"minimum": -128,
			"maximum": 127
		},
		"kerning": {
			"title": "Kerning offset",
			"description": "Offset to add to the x coordinate of each character. Can be negative.",
			"type": "integer",
			"minimum": -128,
			"maximum": 127
		},
		"characterSizes": {
			"title": "Character list",
			"description": "List of all glyphs in the font texture. Each entry's key must be a string containing a printable Unicode character. Only single-code-point characters are supported.",
			"type": "object",
			"additionalProperties": false,
			"patternProperties": {
				"^[^\\u0000-\\u001f]$": {
					"title": "Character metrics",
					"type": "object",
					"required": [
						"x",
						"y",
						"width",
						"height"
					],
					"additionalProperties": false,
					"properties": {
						"x": {
							"title": "X offset",
							"description": "X coordinate of the glyph's top left corner within the font texture.",
							"type": "integer",
							"minimum": 0,
							"maximum": 255
						},
						"y": {
							"title": "Y offset",
							"description": "Y coordinate of the glyph's top left corner within the font texture.",
							"type": "integer",
							"minimum": 0,
							"maximum": 255
						},
						"width": {
							"title": "Character width",
							"description": "Width of the glyph in pixels.",
							"type": "integer",
							"minimum": 0,
							"maximum": 127
						},
						"height": {
							"title": "Character height",
							"description": "Height of the glyph in pixels.",
							"type": "integer",
							"minimum": 0,
							"maximum": 127
						},
						"icon": {
							"title": "Colored icon flag",
							"description": "If true, the glyph will not be colorized when drawing colored text. Useful for glyphs that are not monochrome such as icons or emoji.",
							"type": "boolean"
						}
					}
				}
			}
		}
	}
}

=== NaokiS28/GenV/assets/fonts/roboto/roboto-16.json
{
	"$schema": "../../../schema/fonts.json",
	"fontSize": 	  16,
	"spaceWidth":      4,
	"tabWidth":       32,
	"lineHeight":     10,
	"baselineOffset": -1,
	"kerning": 0,
	"flags": [],

	"characterSizes": {
		" ":  { "x":  0, "y":  0, "width": 4, "height": 16 },
		"!":  { "x":  6, "y":  0, "width": 2, "height": 16 },
		"\"": { "x": 12, "y":  0, "width": 4, "height": 16 },
		"#":  { "x": 18, "y":  0, "width": 6, "height": 16 },
		"$":  { "x": 24, "y":  0, "width": 6, "height": 16 },
		"%":  { "x": 30, "y":  0, "width": 6, "height": 16 },
		"&":  { "x": 36, "y":  0, "width": 6, "height": 16 },
		"'":  { "x": 42, "y":  0, "width": 2, "height": 16 },
		"(":  { "x": 48, "y":  0, "width": 3, "height": 16 },
		")":  { "x": 54, "y":  0, "width": 3, "height": 16 },
		"*":  { "x": 60, "y":  0, "width": 4, "height": 16 },
		"+":  { "x": 66, "y":  0, "width": 6, "height": 16 },
		",":  { "x": 72, "y":  0, "width": 3, "height": 16 },
		"-":  { "x": 78, "y":  0, "width": 6, "height": 16 },
		".":  { "x": 84, "y":  0, "width": 2, "height": 16 },
		"/":  { "x": 90, "y":  0, "width": 6, "height": 16 },
		"0":  { "x":  0, "y": 10, "width": 6, "height": 16 },
		"1":  { "x":  6, "y": 10, "width": 6, "height": 16 },
		"2":  { "x": 12, "y": 10, "width": 6, "height": 16 },
		"3":  { "x": 18, "y": 10, "width": 6, "height": 16 },
		"4":  { "x": 24, "y": 10, "width": 6, "height": 16 },
		"5":  { "x": 30, "y": 10, "width": 6, "height": 16 },
		"6":  { "x": 36, "y": 10, "width": 6, "height": 16 },
		"7":  { "x": 42, "y": 10, "width": 6, "height": 16 },
		"8":  { "x": 48, "y": 10, "width": 6, "height": 16 },
		"9":  { "x": 54, "y": 10, "width": 6, "height": 16 },
		":":  { "x": 60, "y": 10, "width": 2, "height": 16 },
		";":  { "x": 66, "y": 10, "width": 3, "height": 16 },
		"<":  { "x": 72, "y": 10, "width": 6, "height": 16 },
		"=":  { "x": 78, "y": 10, "width": 6, "height": 16 },
		">":  { "x": 84, "y": 10, "width": 6, "height": 16 },
		"?":  { "x": 90, "y": 10, "width": 6, "height": 16 },
		"@":  { "x":  0, "y": 20, "width": 6, "height": 16 },
		"A":  { "x":  6, "y": 20, "width": 6, "height": 16 },
		"B":  { "x": 12, "y": 20, "width": 6, "height": 16 },
		"C":  { "x": 18, "y": 20, "width": 6, "height": 16 },
		"D":  { "x": 24, "y": 20, "width": 6, "height": 16 },
		"E":  { "x": 30, "y": 20, "width": 6, "height": 16 },
		"F":  { "x": 36, "y": 20, "width": 6, "height": 16 },
		"G":  { "x": 42, "y": 20, "width": 6, "height": 16 },
		"H":  { "x": 48, "y": 20, "width": 6, "height": 16 },
		"I":  { "x": 54, "y": 20, "width": 4, "height": 16 },
		"J":  { "x": 60, "y": 20, "width": 5, "height": 16 },
		"K":  { "x": 66, "y": 20, "width": 6, "height": 16 },
		"L":  { "x": 72, "y": 20, "width": 6, "height": 16 },
		"M":  { "x": 78, "y": 20, "width": 6, "height": 16 },
		"N":  { "x": 84, "y": 20, "width": 6, "height": 16 },
		"O":  { "x": 90, "y": 20, "width": 6, "height": 16 },
		"P":  { "x":  0, "y": 30, "width": 6, "height": 16 },
		"Q":  { "x":  6, "y": 30, "width": 6, "height": 16 },
		"R":  { "x": 12, "y": 30, "width": 6, "height": 16 },
		"S":  { "x": 18, "y": 30, "width": 6, "height": 16 },
		"T":  { "x": 24, "y": 30, "width": 6, "height": 16 },
		"U":  { "x": 30, "y": 30, "width": 6, "height": 16 },
		"V":  { "x": 36, "y": 30, "width": 6, "height": 16 },
		"W":  { "x": 42, "y": 30, "width": 6, "height": 16 },
		"X":  { "x": 48, "y": 30, "width": 6, "height": 16 },
		"Y":  { "x": 54, "y": 30, "width": 6, "height": 16 },
		"Z":  { "x": 60, "y": 30, "width": 6, "height": 16 },
		"[":  { "x": 66, "y": 30, "width": 3, "height": 16 },
		"\\": { "x": 72, "y": 30, "width": 6, "height": 16 },
		"]":  { "x": 78, "y": 30, "width": 3, "height": 16 },
		"^":  { "x": 84, "y": 30, "width": 4, "height": 16 },
		"_":  { "x": 90, "y": 30, "width": 6, "height": 16 },
		"`":  { "x":  0, "y": 40, "width": 3, "height": 16 },
		"a":  { "x":  6, "y": 40, "width": 6, "height": 16 },
		"b":  { "x": 12, "y": 40, "width": 6, "height": 16 },
		"c":  { "x": 18, "y": 40, "width": 6, "height": 16 },
		"d":  { "x": 24, "y": 40, "width": 6, "height": 16 },
		"e":  { "x": 30, "y": 40, "width": 6, "height": 16 },
		"f":  { "x": 36, "y": 40, "width": 5, "height": 16 },
		"g":  { "x": 42, "y": 40, "width": 6, "height": 16 },
		"h":  { "x": 48, "y": 40, "width": 5, "height": 16 },
		"i":  { "x": 54, "y": 40, "width": 2, "height": 16 },
		"j":  { "x": 60, "y": 40, "width": 4, "height": 16 },
		"k":  { "x": 66, "y": 40, "width": 5, "height": 16 },
		"l":  { "x": 72, "y": 40, "width": 2, "height": 16 },
		"m":  { "x": 78, "y": 40, "width": 6, "height": 16 },
		"n":  { "x": 84, "y": 40, "width": 5, "height": 16 },
		"o":  { "x": 90, "y": 40, "width": 6, "height": 16 },
		"p":  { "x":  0, "y": 50, "width": 6, "height": 16 },
		"q":  { "x":  6, "y": 50, "width": 6, "height": 16 },
		"r":  { "x": 12, "y": 50, "width": 6, "height": 16 },
		"s":  { "x": 18, "y": 50, "width": 6, "height": 16 },
		"t":  { "x": 24, "y": 50, "width": 5, "height": 16 },
		"u":  { "x": 30, "y": 50, "width": 5, "height": 16 },
		"v":  { "x": 36, "y": 50, "width": 6, "height": 16 },
		"w":  { "x": 42, "y": 50, "width": 6, "height": 16 },
		"x":  { "x": 48, "y": 50, "width": 6, "height": 16 },
		"y":  { "x": 54, "y": 50, "width": 6, "height": 16 },
		"z":  { "x": 60, "y": 50, "width": 5, "height": 16 },
		"{":  { "x": 66, "y": 50, "width": 4, "height": 16 },
		"|":  { "x": 72, "y": 50, "width": 2, "height": 16 },
		"}":  { "x": 78, "y": 50, "width": 4, "height": 16 },
		"~":  { "x": 84, "y": 50, "width": 6, "height": 16 }

	}
}
